package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pmezard/go-difflib/difflib"
)

const goPluginVersion = "v1.36.12"
const grpcPluginVersion = "v1.6.2"

func main() {
	if err := run("."); err != nil {
		fmt.Fprintln(os.Stderr, "protogen:", err)
		os.Exit(1)
	}
}

func run(root string) error {
	inputs, err := protoFiles(filepath.Join(root, "api"))
	if err != nil {
		return err
	}
	output, err := os.MkdirTemp("", "proto-output-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(output)
	if len(inputs) > 0 {
		modulePath, err := readModulePath(filepath.Join(root, "go.mod"))
		if err != nil {
			return err
		}
		compiler, err := exec.LookPath("protoc")
		if err != nil {
			return errors.New("protoc is required for api/*.proto; install protobuf (brew install protobuf or apt install protobuf-compiler)")
		}
		toolsDir, err := filepath.Abs(filepath.Join(root, ".tools"))
		if err != nil {
			return err
		}
		goPlugin, err := ensurePlugin(toolsDir, "protoc-gen-go", "google.golang.org/protobuf/cmd/protoc-gen-go", goPluginVersion)
		if err != nil {
			return err
		}
		grpcPlugin, err := ensurePlugin(toolsDir, "protoc-gen-go-grpc", "google.golang.org/grpc/cmd/protoc-gen-go-grpc", grpcPluginVersion)
		if err != nil {
			return err
		}
		args := []string{"-I.", "--plugin=protoc-gen-go=" + goPlugin, "--plugin=protoc-gen-go-grpc=" + grpcPlugin, "--go_out=" + output, "--go_opt=module=" + modulePath, "--go-grpc_out=" + output, "--go-grpc_opt=module=" + modulePath}
		if info, err := os.Stat(filepath.Join(root, "third_party")); err == nil && info.IsDir() {
			args = append(args, "-Ithird_party")
		}
		for _, input := range inputs {
			relative, err := filepath.Rel(root, input)
			if err != nil {
				return err
			}
			source := filepath.ToSlash(relative)
			mapping, err := serviceMapping(source, modulePath)
			if err != nil {
				return err
			}
			args = append(args, "--go_opt=M"+mapping, "--go-grpc_opt=M"+mapping, source)
		}
		command := exec.Command(compiler, args...)
		command.Dir = root
		if data, err := command.CombinedOutput(); err != nil {
			return fmt.Errorf("compile proto: %w: %s", err, strings.TrimSpace(string(data)))
		}
	}
	return syncGenerated(root, output)
}

func protoFiles(dir string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
		if errors.Is(err, os.ErrNotExist) && path == dir {
			return nil
		}
		if err != nil {
			return err
		}
		if entry.IsDir() && strings.HasPrefix(entry.Name(), ".") {
			return filepath.SkipDir
		}
		if !entry.IsDir() && strings.HasSuffix(path, ".proto") {
			files = append(files, path)
		}
		return nil
	})
	sort.Strings(files)
	return files, err
}

func ensurePlugin(dir, name, module, version string) (string, error) {
	executable := filepath.Join(dir, name)
	if output, err := exec.Command(executable, "--version").Output(); err == nil && strings.HasSuffix(strings.TrimSpace(string(output)), strings.TrimPrefix(version, "v")) {
		return executable, nil
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	fmt.Printf("install %s %s\n", name, version)
	command := exec.Command("go", "install", module+"@"+version)
	command.Env = append(os.Environ(), "GOBIN="+dir)
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return "", fmt.Errorf("install %s: %w", name, err)
	}
	return executable, nil
}

func generatedFiles(root string) (map[string][]byte, error) {
	found := map[string][]byte{}
	dir := filepath.Join(root, "api")
	err := filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
		if errors.Is(err, os.ErrNotExist) && path == dir {
			return nil
		}
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".pb.go") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if bytes.HasPrefix(data, []byte("// Code generated by protoc-gen-go")) {
			relative, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			found[relative] = data
		}
		return nil
	})
	return found, err
}

func syncGenerated(root, output string) error {
	// Validate destinations before modifying existing generated files.
	if err := validateOutput(output); err != nil {
		return err
	}
	current, err := generatedFiles(root)
	if err != nil {
		return err
	}
	next, err := generatedFiles(output)
	if err != nil {
		return err
	}
	names := make([]string, 0, len(next)+len(current))
	for name := range next {
		names = append(names, name)
	}
	for name := range current {
		if _, exists := next[name]; !exists {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		target := filepath.Join(root, name)
		data, exists := next[name]
		if existing, err := os.ReadFile(target); err == nil && !bytes.HasPrefix(existing, []byte("// Code generated by protoc-gen-go")) {
			return fmt.Errorf("refuse to replace non-generated file %s", target)
		}
		if exists {
			if err := showDiff(target, data); err != nil {
				return err
			}
			if err := writeAtomic(target, data); err != nil {
				return err
			}
		} else {
			if err := showDiff(target, nil); err != nil {
				return err
			}
			if err := os.Remove(target); err != nil {
				return err
			}
			fmt.Printf("delete %s\n", target)
		}
	}
	if len(names) == 0 {
		fmt.Println("proto unchanged: no service definitions")
	}
	return nil
}

func writeAtomic(output string, source []byte) error {
	current, err := os.ReadFile(output)
	if err == nil && bytes.Equal(current, source) {
		return nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read generated proto: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(output), ".proto.gen-*.go")
	if err != nil {
		return fmt.Errorf("create generated proto: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if _, err := temporary.Write(source); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write generated proto: %w", err)
	}
	if err := temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("set generated proto permissions: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close generated proto: %w", err)
	}
	if err := os.Rename(temporaryPath, output); err != nil {
		return fmt.Errorf("replace generated proto: %w", err)
	}
	return nil
}

func showDiff(output string, source []byte) error {
	current, err := os.ReadFile(output)
	if errors.Is(err, os.ErrNotExist) {
		fmt.Printf("create %s\n", output)
		return nil
	}
	if err != nil {
		return fmt.Errorf("read generated proto: %w", err)
	}
	if bytes.Equal(current, source) {
		fmt.Printf("%s unchanged\n", output)
		return nil
	}
	diff, err := difflib.GetUnifiedDiffString(difflib.UnifiedDiff{
		A:        difflib.SplitLines(string(current)),
		B:        difflib.SplitLines(string(source)),
		FromFile: output,
		ToFile:   output + " (generated)",
		Context:  3,
	})
	if err != nil {
		return fmt.Errorf("render proto diff: %w", err)
	}
	fmt.Print(diff)
	return nil
}

func readModulePath(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read go module: %w", err)
	}
	for _, line := range strings.Split(string(content), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", errors.New("go module path not found")
}

func validateOutput(output string) error {
	return filepath.WalkDir(output, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".pb.go") {
			return nil
		}
		relative, err := filepath.Rel(output, path)
		if err != nil {
			return err
		}
		parts := strings.Split(filepath.ToSlash(relative), "/")
		if len(parts) < 3 || parts[0] != "api" {
			return fmt.Errorf("go_package must generate into api/<service>, got %s", relative)
		}
		for _, part := range parts[:len(parts)-1] {
			if strings.HasSuffix(part, "-proto") {
				return fmt.Errorf("go_package must not generate into a proto source directory: %s", relative)
			}
		}
		return nil
	})
}

// Map Go imports locally while preserving the provider's Proto contract.
func serviceMapping(source, modulePath string) (string, error) {
	parts := strings.Split(source, "/")
	if len(parts) < 3 || parts[0] != "api" || !strings.HasSuffix(parts[1], "-proto") {
		return "", fmt.Errorf("proto sources must be under api/<service>-proto: %s", source)
	}
	service := strings.TrimSuffix(parts[1], "-proto")
	alias := strings.ReplaceAll(service, "-", "_")
	if !token.IsIdentifier(alias) {
		return "", fmt.Errorf("invalid proto service directory: %s", parts[1])
	}
	return source + "=" + modulePath + "/api/" + service + ";" + alias, nil
}
