package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func writeFile(t *testing.T, path, text string, mode os.FileMode) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(text), mode); err != nil {
		t.Fatal(err)
	}
}

func TestRunGeneratesAndRemovesStaleFiles(t *testing.T) {
	root := t.TempDir()
	if err := run(root); err != nil {
		t.Fatal(err)
	}
	compiler := filepath.Join(t.TempDir(), "protoc")
	writeFile(t, compiler, `#!/bin/sh
for arg in "$@"; do
 case "$arg" in
  --go_out=*) out="${arg#--go_out=}" ;;
  --go_opt=module=example.com/service) go_module=yes ;;
  --go-grpc_opt=module=example.com/service) grpc_module=yes ;;
  *source_relative*) exit 1 ;;
 esac
done
test "$go_module" = yes && test "$grpc_module" = yes || exit 1
mkdir -p "$out/api/user"
printf '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage user\n' > "$out/api/user/user.pb.go"
printf '// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage user\n' > "$out/api/user/user_grpc.pb.go"
`, 0755)
	t.Setenv("PATH", filepath.Dir(compiler)+string(os.PathListSeparator)+os.Getenv("PATH"))
	writeFile(t, filepath.Join(root, ".tools/protoc-gen-go"), "#!/bin/sh\necho protoc-gen-go v1.36.12\n", 0755)
	writeFile(t, filepath.Join(root, ".tools/protoc-gen-go-grpc"), "#!/bin/sh\necho protoc-gen-go-grpc 1.6.2\n", 0755)
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/service\n", 0644)
	input := filepath.Join(root, "api/user-proto/user.proto")
	writeFile(t, input, "syntax = \"proto3\";", 0644)
	if err := run(root); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(root, "api/user/user.pb.go")
	original, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if err := run(root); err != nil {
		t.Fatal(err)
	}
	writeFile(t, compiler, "#!/bin/sh\necho invalid proto >&2\nexit 1\n", 0755)
	if err := run(root); err == nil || !strings.Contains(err.Error(), "compile proto") {
		t.Fatalf("compiler failure: %v", err)
	}
	actual, _ := os.ReadFile(output)
	if string(actual) != string(original) {
		t.Fatal("compiler failure changed generated files")
	}
	if err := os.Remove(input); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(root, "api/user/manual.pb.go"), "package user\n", 0644)
	if err := run(root); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(output); !os.IsNotExist(err) {
		t.Fatal("stale file remained")
	}
	if _, err := os.Stat(filepath.Join(root, "api/user/manual.pb.go")); err != nil {
		t.Fatal("manual file removed")
	}
}

func TestProtectionAndToolErrors(t *testing.T) {
	root, output := t.TempDir(), t.TempDir()
	path := "api/user/test.pb.go"
	writeFile(t, filepath.Join(root, path), "package manual\n", 0644)
	writeFile(t, filepath.Join(output, path), "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage user\n", 0644)
	if err := syncGenerated(root, output); err == nil {
		t.Fatal("manual file overwritten")
	}
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/service\n", 0644)
	writeFile(t, filepath.Join(root, "api/test-proto/test.proto"), "syntax = \"proto3\";", 0644)
	t.Setenv("PATH", t.TempDir())
	if err := run(root); err == nil || !strings.Contains(err.Error(), "protoc is required") {
		t.Fatalf("missing compiler: %v", err)
	}
	fakeGo := filepath.Join(t.TempDir(), "go")
	writeFile(t, fakeGo, "#!/bin/sh\nexit 1\n", 0755)
	t.Setenv("PATH", filepath.Dir(fakeGo))
	if _, err := ensurePlugin(t.TempDir(), "missing", "invalid.example/plugin", "v1.0.0"); err == nil {
		t.Fatal("failed installation accepted")
	}
}

func TestOutputLayoutValidation(t *testing.T) {
	root, output := t.TempDir(), t.TempDir()
	old := filepath.Join(root, "api/user/v1/old.pb.go")
	content := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage user\n"
	writeFile(t, old, content, 0644)
	for _, bad := range []string{"internal/user/user.pb.go", "api/user-proto/user.pb.go"} {
		invalid := filepath.Join(output, bad)
		writeFile(t, invalid, content, 0644)
		if err := syncGenerated(root, output); err == nil {
			t.Fatalf("invalid output accepted: %s", bad)
		}
		if data, err := os.ReadFile(old); err != nil || string(data) != content {
			t.Fatal("invalid layout changed existing generated files")
		}
		if err := os.Remove(invalid); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, filepath.Join(output, "api/user/user.pb.go"), content, 0644)
	if err := syncGenerated(root, output); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(old); !os.IsNotExist(err) {
		t.Fatal("old output was not removed")
	}
	if _, err := os.Stat(filepath.Join(root, "api/user/user.pb.go")); err != nil {
		t.Fatal(err)
	}
}

func TestServiceMapping(t *testing.T) {
	got, err := serviceMapping("api/order-service-proto/user.proto", "example.com/consumer")
	if err != nil || got != "api/order-service-proto/user.proto=example.com/consumer/api/order-service;order_service" {
		t.Fatalf("mapping: %s %v", got, err)
	}
	for _, source := range []string{"api/user.proto", "api/user/user.proto", "api/-proto/user.proto", "api/123-proto/user.proto"} {
		if _, err := serviceMapping(source, "example.com/consumer"); err == nil {
			t.Fatalf("invalid path accepted: %s", source)
		}
	}
}

func TestExternalContractsGenerateLocally(t *testing.T) {
	if _, err := exec.LookPath("protoc"); err != nil {
		t.Skip("protoc not installed")
	}
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/consumer\n", 0644)
	remote := `syntax = "proto3";
package remote_service.v1;
option go_package = "example.com/provider/api/remote-service;remote_service";
message User { int64 id = 1; }
service UserService { rpc GetUser(User) returns (User); }
`
	local := `syntax = "proto3";
package consumer.v1;
option go_package = "example.com/consumer/api/consumer;consumer";
import "api/remote-service-proto/user.proto";
message User { remote_service.v1.User remote = 1; }
service UserService { rpc GetUser(User) returns (User); }
`
	source := filepath.Join(root, "api/remote-service-proto/user.proto")
	writeFile(t, source, remote, 0644)
	writeFile(t, filepath.Join(root, "api/consumer-proto/user.proto"), local, 0644)
	if err := run(root); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"consumer", "remote-service"} {
		for _, file := range []string{"user.pb.go", "user_grpc.pb.go"} {
			if _, err := os.Stat(filepath.Join(root, "api", name, file)); err != nil {
				t.Fatal(err)
			}
		}
	}
	generated, err := os.ReadFile(filepath.Join(root, "api/consumer/user.pb.go"))
	if err != nil || !strings.Contains(string(generated), `"example.com/consumer/api/remote-service"`) {
		t.Fatalf("external import not remapped: %v", err)
	}
	actual, err := os.ReadFile(source)
	if err != nil || string(actual) != remote {
		t.Fatal("external source was modified")
	}
}
