// Code generated by configgen; DO NOT EDIT.

package config

import "time"

type Config struct {
	Auth        AuthConfig        `koanf:"auth"`
	Database    DatabaseConfig    `koanf:"database"`
	GRPC        GRPCConfig        `koanf:"grpc"`
	HTTP        HTTPConfig        `koanf:"http"`
	Idempotency IdempotencyConfig `koanf:"idempotency"`
	Log         LogConfig         `koanf:"log"`
	Pagination  PaginationConfig  `koanf:"pagination"`
	Redact      RedactConfig      `koanf:"redact"`
	Redis       RedisConfig       `koanf:"redis"`
	Server      ServerConfig      `koanf:"server"`
	Tracer      TracerConfig      `koanf:"tracer"`
}

type AuthConfig struct {
	Authorization       AuthAuthorizationConfig       `koanf:"authorization"`
	ChallengeEncryption AuthChallengeEncryptionConfig `koanf:"challengeEncryption"`
	Jwt                 AuthJwtConfig                 `koanf:"jwt"`
	PasswordChange      AuthPasswordChangeConfig      `koanf:"passwordChange"`
	PointCaptcha        AuthPointCaptchaConfig        `koanf:"pointCaptcha"`
	Refresh             AuthRefreshConfig             `koanf:"refresh"`
	Switches            AuthSwitchesConfig            `koanf:"switches"`
}

type AuthAuthorizationConfig struct {
	Enabled bool `koanf:"enabled"`
}

type AuthChallengeEncryptionConfig struct {
	KeyID          string        `koanf:"keyId"`
	PrivateKeyFile string        `koanf:"privateKeyFile"`
	TTL            time.Duration `koanf:"ttl"`
}

type AuthJwtConfig struct {
	Issuer   string        `koanf:"issuer"`
	Key      string        `koanf:"key"`
	Lifetime time.Duration `koanf:"lifetime"`
}

type AuthPasswordChangeConfig struct {
	FailureTTL    time.Duration `koanf:"failureTTL"`
	LockThreshold int           `koanf:"lockThreshold"`
	Threshold     int           `koanf:"threshold"`
}

type AuthPointCaptchaConfig struct {
	Height    int           `koanf:"height"`
	Threshold int           `koanf:"threshold"`
	Tolerance int           `koanf:"tolerance"`
	TTL       time.Duration `koanf:"ttl"`
	Width     int           `koanf:"width"`
}

type AuthRefreshConfig struct {
	RememberLifetime time.Duration `koanf:"rememberLifetime"`
	SessionLifetime  time.Duration `koanf:"sessionLifetime"`
}

type AuthSwitchesConfig struct {
	PasswordResetRequired      bool `koanf:"passwordResetRequired"`
	ProtectCaptchaDictionaries bool `koanf:"protectCaptchaDictionaries"`
	ProtectSuper               bool `koanf:"protectSuper"`
}

type DatabaseConfig struct {
	AutoCreate      bool          `koanf:"autoCreate"`
	ConnMaxLifetime time.Duration `koanf:"connMaxLifetime"`
	Driver          string        `koanf:"driver"`
	DSN             string        `koanf:"dsn"`
	MaxIdleConns    int           `koanf:"maxIdleConns"`
	MaxOpenConns    int           `koanf:"maxOpenConns"`
	Migrate         bool          `koanf:"migrate"`
}

type GRPCConfig struct {
	Addr            string        `koanf:"addr"`
	Reflection      bool          `koanf:"reflection"`
	ShutdownTimeout time.Duration `koanf:"shutdownTimeout"`
	Timeout         time.Duration `koanf:"timeout"`
}

type HTTPConfig struct {
	Addr              string             `koanf:"addr"`
	Docs              HTTPDocsConfig     `koanf:"docs"`
	IdleTimeout       time.Duration      `koanf:"idleTimeout"`
	Profiler          HTTPProfilerConfig `koanf:"profiler"`
	ReadHeaderTimeout time.Duration      `koanf:"readHeaderTimeout"`
	Timeout           time.Duration      `koanf:"timeout"`
}

type HTTPDocsConfig struct {
	Enabled bool                        `koanf:"enabled"`
	Servers []HTTPDocsServersItemConfig `koanf:"servers"`
}

type HTTPDocsServersItemConfig struct {
	Description string `koanf:"description"`
	URL         string `koanf:"url"`
}

type HTTPProfilerConfig struct {
	Addr    string `koanf:"addr"`
	Enabled bool   `koanf:"enabled"`
}

type IdempotencyConfig struct {
	TTL time.Duration `koanf:"ttl"`
}

type LogConfig struct {
	Level string `koanf:"level"`
}

type PaginationConfig struct {
	MaxP int `koanf:"maxP"`
	MaxS int `koanf:"maxS"`
}

type RedactConfig struct {
	Keys []string `koanf:"keys"`
}

type RedisConfig struct {
	DSN    string `koanf:"dsn"`
	Prefix string `koanf:"prefix"`
}

type ServerConfig struct {
	Name string `koanf:"name"`
}

type TracerConfig struct {
	Enabled bool             `koanf:"enabled"`
	OTLP    TracerOTLPConfig `koanf:"otlp"`
	Ratio   float64          `koanf:"ratio"`
	Stdout  bool             `koanf:"stdout"`
}

type TracerOTLPConfig struct {
	Endpoint string `koanf:"endpoint"`
	Insecure bool   `koanf:"insecure"`
}
