// Code generated by modulegen; DO NOT EDIT.

package app

import (
	"auth/internal/modules"
)

func (a *Application) generatedModules() ([]modules.HTTPModule, []modules.GRPCModule) {
	var httpModules []modules.HTTPModule
	var grpcModules []modules.GRPCModule
	module0 := a.actionModule
	httpModules = append(httpModules, module0)
	module1 := a.authModule
	httpModules = append(httpModules, module1)
	module2 := a.dictionaryModule
	httpModules = append(httpModules, module2)
	module3 := a.roleModule
	httpModules = append(httpModules, module3)
	module4 := a.userModule
	httpModules = append(httpModules, module4)
	module5 := a.groupModule
	httpModules = append(httpModules, module5)
	module6 := a.whitelistModule
	httpModules = append(httpModules, module6)
	return httpModules, grpcModules
}
