package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/knadh/koanf/parsers/yaml"
	"github.com/knadh/koanf/providers/file"
	"github.com/knadh/koanf/v2"
	"github.com/pmezard/go-difflib/difflib"
	jsonstruct "github.com/twpayne/go-jsonstruct/v3"
)

var durationField = regexp.MustCompile("(?m)^(\\s+[A-Za-z0-9_]*(?:Timeout|Duration|Lifetime|Interval|TTL)\\s+)string(\\s+`koanf:)")

func main() {
	configDir := flag.String("config-dir", "conf", "configuration directory")
	output := flag.String("output", "internal/common/config/config.gen.go", "generated Go file")
	flag.Parse()
	if err := run(*configDir, *output); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "configgen: %v\n", err)
		os.Exit(1)
	}
}

func run(configDir, output string) error {
	values := koanf.New(".")
	paths, err := yamlFiles(configDir)
	if err != nil {
		return err
	}
	for _, path := range paths {
		if err := values.Load(file.Provider(path), yaml.Parser()); err != nil {
			return fmt.Errorf("load %q: %w", path, err)
		}
	}

	generator := jsonstruct.NewGenerator(
		jsonstruct.WithPackageName("config"),
		jsonstruct.WithTypeName("Config"),
		jsonstruct.WithStructTagName("koanf"),
		jsonstruct.WithOmitEmptyTags(jsonstruct.OmitEmptyTagsNever),
		jsonstruct.WithOmitZeroTags(jsonstruct.OmitZeroTagsNever),
		jsonstruct.WithExtraAbbreviations("DSN", "OTLP", "TTL", "GRPC"),
		jsonstruct.WithFileHeader("// Code generated by configgen; DO NOT EDIT."),
	)
	generator.ObserveValue(values.Raw())
	source, err := generator.Generate()
	if err != nil {
		return fmt.Errorf("generate go config: %w", err)
	}
	source, err = addDurationTypes(source)
	if err != nil {
		return err
	}
	source, err = nameNestedStructs(source)
	if err != nil {
		return err
	}
	if err := showDiff(output, source); err != nil {
		return err
	}
	return writeAtomic(output, source)
}

func addDurationTypes(source []byte) ([]byte, error) {
	converted := durationField.ReplaceAll(source, []byte("${1}time.Duration${2}"))
	if bytes.Equal(converted, source) {
		return source, nil
	}
	if !bytes.Contains(converted, []byte("\"time\"")) {
		converted = bytes.Replace(converted, []byte("package config\n"), []byte("package config\n\nimport \"time\"\n"), 1)
	}
	formatted, err := format.Source(converted)
	if err != nil {
		return nil, fmt.Errorf("format generated config: %w", err)
	}
	return formatted, nil
}

func nameNestedStructs(source []byte) ([]byte, error) {
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, "config.gen.go", source, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse generated config: %w", err)
	}

	var root *ast.StructType
	for _, declaration := range file.Decls {
		generic, ok := declaration.(*ast.GenDecl)
		if !ok || generic.Tok != token.TYPE {
			continue
		}
		for _, specification := range generic.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if ok && typeSpec.Name.Name == "Config" {
				root, _ = typeSpec.Type.(*ast.StructType)
			}
		}
	}
	if root == nil {
		return nil, errors.New("generated config struct not found")
	}

	used := map[string]struct{}{"Config": {}}
	declarations := make([]ast.Decl, 0, len(root.Fields.List))
	for _, field := range root.Fields.List {
		if len(field.Names) != 1 {
			continue
		}
		typeExpr, nested, err := liftNestedType(field.Type, field.Names[0].Name, used)
		if err != nil {
			return nil, err
		}
		field.Type = typeExpr
		declarations = append(declarations, nested...)
	}
	file.Decls = append(file.Decls, declarations...)

	var output bytes.Buffer
	if err := format.Node(&output, fileSet, file); err != nil {
		return nil, fmt.Errorf("format named config structs: %w", err)
	}
	return bytes.ReplaceAll(output.Bytes(), []byte("}\ntype "), []byte("}\n\ntype ")), nil
}

func liftNestedType(expr ast.Expr, baseName string, used map[string]struct{}) (ast.Expr, []ast.Decl, error) {
	switch typed := expr.(type) {
	case *ast.StructType:
		children := make([]ast.Decl, 0)
		for _, field := range typed.Fields.List {
			if len(field.Names) != 1 {
				continue
			}
			childType, declarations, err := liftNestedType(field.Type, baseName+field.Names[0].Name, used)
			if err != nil {
				return nil, nil, err
			}
			field.Type = childType
			children = append(children, declarations...)
		}
		typeName := baseName + "Config"
		if _, exists := used[typeName]; exists {
			return nil, nil, fmt.Errorf("generated config type %s is duplicated", typeName)
		}
		used[typeName] = struct{}{}
		declaration := &ast.GenDecl{
			Tok: token.TYPE,
			Specs: []ast.Spec{&ast.TypeSpec{
				Name: ast.NewIdent(typeName),
				Type: typed,
			}},
		}
		return ast.NewIdent(typeName), append([]ast.Decl{declaration}, children...), nil
	case *ast.ArrayType:
		element, declarations, err := liftNestedType(typed.Elt, baseName+"Item", used)
		if err != nil {
			return nil, nil, err
		}
		typed.Elt = element
		return typed, declarations, nil
	case *ast.StarExpr:
		value, declarations, err := liftNestedType(typed.X, baseName, used)
		if err != nil {
			return nil, nil, err
		}
		typed.X = value
		return typed, declarations, nil
	case *ast.MapType:
		value, declarations, err := liftNestedType(typed.Value, baseName+"Value", used)
		if err != nil {
			return nil, nil, err
		}
		typed.Value = value
		return typed, declarations, nil
	default:
		return expr, nil, nil
	}
}

func showDiff(output string, source []byte) error {
	current, err := os.ReadFile(output)
	if errors.Is(err, os.ErrNotExist) {
		fmt.Printf("create %s\n", output)
		return nil
	}
	if err != nil {
		return fmt.Errorf("read existing generated config: %w", err)
	}
	if bytes.Equal(current, source) {
		fmt.Printf("%s unchanged\n", output)
		return nil
	}
	diff, err := difflib.GetUnifiedDiffString(difflib.UnifiedDiff{
		A:        difflib.SplitLines(string(current)),
		B:        difflib.SplitLines(string(source)),
		FromFile: output,
		ToFile:   output + " (generated)",
		Context:  3,
	})
	if err != nil {
		return fmt.Errorf("render config diff: %w", err)
	}
	fmt.Print(diff)
	return nil
}

func yamlFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read config directory %q: %w", dir, err)
	}
	paths := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		ext := strings.ToLower(filepath.Ext(entry.Name()))
		if ext == ".yml" || ext == ".yaml" {
			paths = append(paths, filepath.Join(dir, entry.Name()))
		}
	}
	sort.Strings(paths)
	if len(paths) == 0 {
		return nil, fmt.Errorf("no yaml configuration files found in %q", dir)
	}
	return paths, nil
}

func writeAtomic(output string, source []byte) error {
	dir := filepath.Dir(output)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	temp, err := os.CreateTemp(dir, ".config.gen-*.go")
	if err != nil {
		return fmt.Errorf("create temporary output: %w", err)
	}
	tempName := temp.Name()
	defer os.Remove(tempName)
	if _, err := temp.Write(source); err != nil {
		_ = temp.Close()
		return fmt.Errorf("write temporary output: %w", err)
	}
	if err := temp.Chmod(0o644); err != nil {
		_ = temp.Close()
		return fmt.Errorf("set output permissions: %w", err)
	}
	if err := temp.Close(); err != nil {
		return fmt.Errorf("close temporary output: %w", err)
	}
	if err := os.Rename(tempName, output); err != nil {
		return fmt.Errorf("replace generated config: %w", err)
	}
	return nil
}
